title: Mesa Verde Condo
dev_email: andy@r210.com
email: sueln15@gmail.com
description: "Mesa Verde Condo"
url: https://mesa-verde-condo.com
github_username:  andyl

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

safe: false

permalink: /blog/:year/:month/:day/:title/

show_downloads: false
google_analytics: TBD

tagline: A comfortable home for Mesa Verde visitors!
paginate:            1
sass:
  sass_dir:         _sass
  style:            :compressed
author: MvCondo

analytics_id: TBD

disqus:
  shortname: TBD

excerpt_separator: <!--more-->
